version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nextjs_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgweb:
    image: sosedoff/pgweb
    environment:
      - PGWEB_DATABASE_URL=postgres://postgres:postgres@postgres:5432/nextjs_db?sslmode=disable
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
